# Generated by Django 2.1.2 on 2018-11-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='open_positions',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='Location.Location'),
        ),
    ]
