# Generated by Django 2.1.2 on 2018-11-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20181121_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='total_positions',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
