# Generated by Django 2.1.2 on 2018-12-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20181209_1439'),
        ('Event', '0008_auto_20181204_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiresSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Skill')),
            ],
        ),
    ]
