# Generated by Django 2.1.2 on 2018-11-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happy2Help', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creditPoints',
            new_name='credit_points',
        ),
    ]
