# Generated by Django 2.1.2 on 2018-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happy2Help', '0002_auto_20181107_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='state',
            field=models.IntegerField(choices=[(1, 'Participated'), (2, 'Applied'), (3, 'Declined'), (4, 'Accepted'), (5, 'Canceled')], default=2),
        ),
    ]
