# Generated by Django 2.1.2 on 2018-12-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='secure_url',
            new_name='url',
        ),
    ]
