# Generated by Django 2.1.2 on 2018-12-09 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_auto_20181204_2349'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_auto_20181121_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('event', 'user')},
        ),
    ]
